config/routes.rb
Rails.application.routes.draw do
  root 'index#landing_page'
  devise_for :users

  # Should move hexmap stuff into its own controller and use index as main landing pages... thinking about future expansion and such
  # Example single route for my goldfish like memory: get 'index/hexmap', to: 'index#hexmap'
  resources :index do
    collection do
      get 'landing_page'
    end
  end

  resources :hex_system do
    collection do
      get 'hexmap'
    end
  end

  resources :sectors, controller:'sector/sectors' do
    resources :permissions, controller: 'sector/permissions'
  end
  resources :systems, controller:'sector/systems' do
    collection do
      get 'bulk_upload'
      post 'process_bulk_upload'
    end
    member do
      patch 'update_allegiance'
    end
    resources :system_notes, controller: 'sector/system_notes'
  end
  resources :factions, controller:'sector/factions'
  resource :profile, only: [:show], controller: 'profiles'

  namespace :admin do
    resources :users do
      member do
        patch :reset_password
      end
    end
  end

end

app/models/sector_model/sector.rb
class SectorModel::Sector < ApplicationRecord
  self.table_name = 'sectors'
  has_many :systems, dependent: :destroy
  has_many :factions, dependent: :destroy
  has_many :sector_permissions, foreign_key: :sector_id, dependent: :destroy
  has_many :permitted_users, through: :sector_permissions, source: :user

  validates :border_width, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 20 }, allow_nil: true
  validates :border_opacity, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 1 }, allow_nil: true
  validates :grid_opacity, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 1 }, allow_nil: true
  validates :show_grid, inclusion: { in: [true, false] }, allow_nil: true
end

app/controllers/sector/factions_controller.rb
class Sector::FactionsController < ApplicationController
  before_action :check_member, only: [:new, :edit, :update, :destroy]
  before_action :presets
   
  def index
    @sector = SectorModel::Sector.find(params[:sector_id])
    if can_view_factions?(@sector, current_user)
      @factions = SectorModel::Faction.where("sector_id = ?", params[:sector_id])
    else
      redirect_back_or_to sector_path(@sector), alert: "You do not have permission to view factions for this sector."
    end
  end

  def show
    @faction = SectorModel::Faction.find(params[:id])
    @sector = @faction.sector
    unless can_view_factions?(@sector, current_user)
      redirect_back_or_to sector_path(@sector), alert: "You do not have permission to view factions for this sector."
    end
  end

  def new
    @sector = SectorModel::Sector.find(params[:sector_id] || params.dig(:sector_model_faction, :sector_id))
    if can_edit_factions?(@sector, current_user)
      @faction = SectorModel::Faction.new
    else
      redirect_back_or_to factions_path(sector_id: @sector.id), alert: "You do not have permission to edit factions."
    end
  end

  def create
    @sector = SectorModel::Sector.find(params[:sector_id] || params.dig(:sector_model_faction, :sector_id))
    if can_edit_factions?(@sector, current_user)
      @faction = SectorModel::Faction.new(faction_params)
      @faction.sector = @sector

      if @faction.save
        respond_to do |format|
          format.html { redirect_to factions_path(sector_id: @sector.id) }
          format.json { render json: @faction, status: :created }
        end
      else
        respond_to do |format|
          format.html { render 'new' }
          format.json { render json: @faction.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_back_or_to factions_path(sector_id: @sector.id), alert: "You do not have permission to edit factions."
    end
  end

  def edit
    @sector = SectorModel::Sector.find(params[:sector_id] || params.dig(:sector_model_faction, :sector_id))
    @faction = SectorModel::Faction.find(params[:id])
    
    unless can_edit_factions?(@sector, current_user)
      redirect_back_or_to factions_path(sector_id: @sector.id), alert: "You do not have permission to edit factions."
    end
  end

  def update
    @sector = SectorModel::Sector.find(params[:sector_id] || params.dig(:sector_model_faction, :sector_id))
    @faction = SectorModel::Faction.find(params[:id])
    
    if can_edit_factions?(@sector, current_user)
      if @faction.update(faction_params)
        redirect_to factions_path(sector_id: @sector.id)
      else
        render 'edit'
      end
    else
      redirect_back_or_to factions_path(sector_id: @sector.id), alert: "You do not have permission to edit factions."
    end
    
  end

  def destroy
    @sector = SectorModel::Sector.find(params[:sector_id] || params[:sector_model_faction][:sector_id])
    @faction = SectorModel::Faction.find(params[:id])
    
    if can_edit_factions?(@sector, current_user)
      @faction.destroy
    else
      redirect_back_or_to factions_path(sector_id: @sector.id), alert: "You do not have permission to delete factions." and return
    end
    
    redirect_to factions_path(sector_id: @sector.id)
  end

  private

  def faction_params
    params.require(:sector_model_faction).permit(:sector_id, :name, :description, :color_code, :created_at, :updated_at)
  end

	def presets
		@page_libs = [:color_picker]
	end
	
end

app/controllers/sector/permissions_controller.rb
class Sector::PermissionsController < ApplicationController
  before_action :set_sector

  def index
    @permissions = @sector.sector_permissions.includes(:user)
  end

  def new
    @permission = @sector.sector_permissions.new
    @users = User.where.not(id: @sector.permitted_users.pluck(:id)).where.not(email: @sector.author)
  end

  def create
    @permission = @sector.sector_permissions.new(permission_params)
    if @permission.save
      redirect_to sector_permissions_path(@sector), notice: 'Permission added successfully.'
    else
      @users = User.where.not(id: @sector.permitted_users.pluck(:id)).where.not(email: @sector.author)
      render :new
    end
  end

  def edit
    @permission = @sector.sector_permissions.find(params[:id])
  end

  def update
    @permission = @sector.sector_permissions.find(params[:id])
    if @permission.update(permission_params)
      redirect_to sector_permissions_path(@sector), notice: 'Permission updated successfully.'
    else
      render :edit
    end
  end

  def destroy
    @permission = @sector.sector_permissions.find(params[:id])
    @permission.destroy
    redirect_to sector_permissions_path(@sector), notice: 'Permission removed successfully.'
  end

  private

  def set_sector
    @sector = SectorModel::Sector.find(params[:sector_id])
    unless @sector.author == current_user.email || current_user.admin?
      redirect_back_or_to sectors_path, alert: 'You do not have permission to manage permissions for this sector.'
    end
  end

  def permission_params
    params.require(:sector_permission).permit(:user_id, :can_view_sector, :can_edit_sector, :can_view_factions, :can_edit_factions, :can_view_systems, :can_edit_systems, :can_view_system_notes, :can_edit_system_notes)
  end
end

app/controllers/sector/sectors_controller.rb
class Sector::SectorsController < ApplicationController
  before_action :check_member, only: [:new, :edit, :update, :destroy]
  before_action :presets, only: [:new, :edit, :create, :update]
   
  def index
    @sectors = SectorModel::Sector.left_outer_joins(:sector_permissions)
                                  .where("sectors.public_view = '1' OR sectors.author = ? OR sector_permissions.user_id = ?", current_user.email, current_user.id)
                                  .distinct
    if current_user.admin?
      @sectors = SectorModel::Sector.all
    end
  end

  def show
    @sector = SectorModel::Sector.find(params[:id])
    unless can_view_sector?(@sector, current_user)
      redirect_back_or_to sectors_path, alert: "You do not have permission to view this sector."
    end
  end

  def new
    @sector = SectorModel::Sector.new
    gon.hex_color = "#f8f9fa"
    gon.border_width = 4
    gon.border_opacity = 0.5
    gon.background_image = nil
    gon.show_grid = true
    gon.grid_opacity = 0.1
    gon.background_images = Dir.glob(Rails.root.join('app', 'assets', 'images', 'backgrounds', '*.svg')).each_with_object({}) do |f, hash|
      filename = File.basename(f)
      hash[filename] = ActionController::Base.helpers.image_path("backgrounds/#{filename}")
    end
  end

  def create
    @sector = SectorModel::Sector.new(sector_params)

    if @sector.save
      redirect_to sectors_path
    else
      render 'new'
    end
  end

  def edit
    @sector = SectorModel::Sector.find(params[:id])
    
    unless can_edit_sector?(@sector, current_user)
      redirect_back_or_to sectors_path, alert: "You do not have permission to edit this sector."
    end

    gon.hex_color = @sector.hex_color.presence || "#f8f9fa"
    gon.border_width = @sector.border_width.presence || 4
    gon.border_opacity = @sector.border_opacity.presence || 0.5
    gon.background_image = @sector.background_image.presence
    gon.show_grid = @sector.show_grid
    gon.grid_opacity = @sector.grid_opacity.presence || 0.1
    gon.background_images = Dir.glob(Rails.root.join('app', 'assets', 'images', 'backgrounds', '*.svg')).each_with_object({}) do |f, hash|
      filename = File.basename(f)
      hash[filename] = ActionController::Base.helpers.image_path("backgrounds/#{filename}")
    end
  end

  def update
    @sector = SectorModel::Sector.find(params[:id])
    
    if can_edit_sector?(@sector, current_user)
      if @sector.update(sector_params)
        redirect_to sectors_path
      else
        render 'edit'
      end
    else
      redirect_back_or_to sectors_path, alert: "You do not have permission to edit this sector."
    end
    
  end

  def destroy
    @sector = SectorModel::Sector.find(params[:id])
    
    if @sector.author == current_user.email || current_user.admin?
      @sector.destroy
    else
      redirect_back_or_to sectors_path, alert: "Only the author can delete this sector." and return
    end
    
    redirect_to sectors_path
  end

  private

  def presets
    @page_libs = [:hexmap]
    
    # Sample data for hexmap preview
    @preview_data = {
      "0" => { n: "System A", q: 1, r: 1, hex_loc: "0101", allegiance: "Faction 1", colour: "#ff5733" },
      "1" => { n: "System B", q: 1, r: 2, hex_loc: "0102", allegiance: "Faction 1", colour: "#ff5733" },
      "2" => { n: "System C", q: 2, r: 1, hex_loc: "0201", allegiance: "Faction 2", colour: "#33ff57" },
      "3" => { n: "System D", q: 2, r: 2, hex_loc: "0202", allegiance: "Faction 2", colour: "#33ff57" }
    }
    gon.data = @preview_data
  end

  def sector_params
    params.require(:sector_model_sector).permit(:author, :name, :public_view, :hex_color, :border_width, :border_opacity, :background_image, :show_grid, :grid_opacity, :created_at, :updated_at)
  end

  # TODO: Add in ability to export an entire sector, its systems, notes, factions, and sector settings.
  #   This should be done in a way that it could later be reimported to recreate that sector.

end

app/controllers/sector/system_notes_controller.rb
class Sector::SystemNotesController < ApplicationController
  before_action :check_member, only: [:new, :edit, :update, :destroy]
   
  def index
    @system = SectorModel::System.find(params[:system_id])
    @sector = @system.sector
    
    @system_notes = visible_system_notes(@system, current_user)
    
    if can_view_systems?(@sector, current_user)
      if params[:partial] == "yes"
        render partial: 'sector/system_notes/system_notes'
      end
    else
      redirect_back_or_to system_path(@system), alert: "You do not have permission to view this system."
    end
  end

  def new
    @system = SectorModel::System.find(params[:system_id])
    @sector = @system.sector
    
    if can_edit_system_notes?(@sector, current_user)
      @system_note = SectorModel::SystemNote.new
      respond_to do |format|
        format.html
        format.js
      end
    else
      redirect_back_or_to system_path(@system), alert: "You do not have permission to edit system notes."
    end
  end

  def create
    @system = SectorModel::System.find(params[:system_id])
    @sector = @system.sector

    if can_edit_system_notes?(@sector, current_user)
      @system_note = SectorModel::SystemNote.new(system_note_params)
      @system_note.system_id = @system.id
      if @system_note.save
        respond_to do |format|
          format.html { redirect_to system_path(@system) }
          format.js { head :no_content }
        end
      else
        respond_to do |format|
          format.html { render 'new' }
          format.js { render partial: 'form', locals: { errors: @system_note.errors }, status: :unprocessable_entity }
        end
      end
    else
      redirect_back_or_to system_path(@system), alert: "You do not have permission to edit system notes."
    end
  end

  def edit
    @system_note = SectorModel::SystemNote.find(params[:id])
    @system = SectorModel::System.find(params[:system_id])
    @sector = @system.sector
    
    unless can_edit_system_notes?(@sector, current_user) && (@system_note.author == current_user.email || @sector.author == current_user.email || current_user.admin?)
      redirect_back_or_to system_path(@system.id), alert: "You do not have permission to edit this system note."
    end

    respond_to do |format|
      format.html
      format.js
    end
  end

  def update
    @system_note = SectorModel::SystemNote.find(params[:id])
    @system = SectorModel::System.find(params[:system_id])
    @sector = @system.sector
    
    if can_edit_system_notes?(@sector, current_user) && (@system_note.author == current_user.email || @sector.author == current_user.email || current_user.admin?)
      if @system_note.update(system_note_params)
        respond_to do |format|
          format.html { redirect_to system_path(@system) }
          format.js { head :no_content }
        end
      else
        respond_to do |format|
          format.html { render 'edit' }
          format.js { render partial: 'form', locals: { errors: @system_note.errors }, status: :unprocessable_entity }
        end
      end
    else
      redirect_back_or_to system_path(@system.id), alert: "You do not have permission to edit this system note."
    end
    
  end

  def destroy
    @system_note = SectorModel::SystemNote.find(params[:id])
    @system = SectorModel::System.find(params[:system_id])
    @sector = @system.sector
    
    if can_edit_system_notes?(@sector, current_user) && (@system_note.author == current_user.email || @sector.author == current_user.email || current_user.admin?)
      @system_note.destroy
    else
      redirect_back_or_to system_path(@system.id), alert: "You do not have permission to delete this system note." and return
    end
    
    redirect_to system_path(@system.id)
  end

  private

  def system_note_params
    params.require(:sector_model_system_note).permit(:system_id, :author, :content, :public_view, :created_at, :updated_at)
  end
  
end

app/helpers/factions_helper.rb
module FactionsHelper
end

app/helpers/sector/sectors_helper.rb
module Sector::SectorsHelper
end

app/helpers/sector/systems_helper.rb
module Sector::SystemsHelper
  def combine_uwp_params(params)
    "#{params[:starport]}#{params[:planet_size]}#{params[:atmosphere]}#{params[:hydrosphere]}#{params[:population]}#{params[:goverment]}#{params[:law]}-#{params[:tech_level]}"
  end
  
  def combine_note_params(params)
    "#{params[:notes1]} #{params[:notes2]} #{params[:notes3]}".rstrip
  end

  def combine_pbg_params(params)
    "#{params[:pop_base]}#{params[:asteroid_belts]}#{params[:gas_giants]}" 
  end
  
end

app/views/sector/factions/edit.html.erb
<% content_for :page_title, 'Edit Faction' %>

<div class="container-fluid">
  <div class="pagetitle">
    <h1>Edit Faction</h1>
    <nav>
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/">Home</a></li>
        <li class="breadcrumb-item"><%= link_to "Sectors", sectors_path %></li>
        <li class="breadcrumb-item"><%= link_to @sector.name, sector_path(@sector) %></li>
        <li class="breadcrumb-item"><%= link_to "Factions", factions_path(sector_id: @sector.id) %></li>
        <li class="breadcrumb-item active">Edit</li>
      </ol>
    </nav>
  </div>

  <section class="section">
    <div class="row justify-content-center">
      <div class="col-lg-8">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">Update Faction Settings</h5>

            <%= form_with model: @faction, url: faction_path(@faction), method: :patch, html: { class: "row g-3" } do |f| %>
              <% if @faction.errors.any? %>
                <div class="col-12">
                  <div class="alert alert-danger alert-dismissible fade show" role="alert">
                    <h4 class="alert-heading"><%= pluralize(@faction.errors.count, "error") %> prohibited this faction from being saved:</h4>
                    <ul class="mb-0">
                      <% @faction.errors.full_messages.each do |message| %>
                        <li><%= message %></li>
                      <% end %>
                    </ul>
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                  </div>
                </div>
              <% end %>

              <%= f.hidden_field :sector_id, value: @sector.id %>
              <%= f.hidden_field :updated_at, value: Time.now %>

              <div class="col-12">
                <%= f.label :name, class: "form-label" %>
                <%= f.text_field :name, class: 'form-control' %>
              </div>

              <div class="col-12">
                <%= f.label :description, class: "form-label" %>
                <%= f.text_area :description, class: 'form-control', rows: 3 %>
              </div>

              <div class="col-12 mt-3">
                <%= f.label :color_code, "Faction Color", class: "form-label d-block" %>
                <%= f.text_field :color_code, id: 'color_picker', class: "form-control" %>
                <div class="form-text">Choose a color to represent this faction on the hexmap.</div>
              </div>

              <div class="text-center mt-4">
                <%= f.submit "Update Faction", class: 'btn btn-primary px-4' %>
                <%= link_to 'Cancel', factions_path(sector_id: @sector.id), class: "btn btn-secondary px-4" %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>

<script>
  $(document).ready(function() {
    $('#color_picker').spectrum({
      preferredFormat: "rgb",
      showInput: true
    });
  });
</script>

app/views/sector/factions/index.html.erb
<% content_for :page_title, 'Factions' %>

<div class="container-fluid">
  <div class="pagetitle">
    <h1>Factions</h1>
    <nav>
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/">Home</a></li>
        <li class="breadcrumb-item"><%= link_to "Sectors", sectors_path %></li>
        <li class="breadcrumb-item"><%= link_to @sector.name, sector_path(@sector) %></li>
        <li class="breadcrumb-item active">Factions</li>
      </ol>
    </nav>
  </div>

  <section class="section">
    <div class="row">
      <div class="col-lg-12">
        <div class="card overflow-auto">
          <div class="card-body">
            <div class="d-flex justify-content-between align-items-center mb-3">
              <h5 class="card-title">Factions for <%= @sector.name %></h5>
              <% if can_edit_factions?(@sector, current_user) %>
                <%= link_to new_faction_path(sector_model_faction: { sector_id: @sector.id }), class: 'btn btn-primary' do %>
                  <i class="bi bi-plus-circle"></i> New Faction
                <% end %>
              <% end %>
            </div>

            <div class="table-responsive">
              <table class="table table-hover align-middle">
                <thead>
                  <tr>
                    <th scope="col">Name</th>
                    <th scope="col">Description</th>
                    <th scope="col" class="text-center">Color</th>
                    <th scope="col" class="text-center">Created</th>
                    <th scope="col" class="text-center">Updated</th>
                    <% if can_edit_factions?(@sector, current_user) %>
                      <th scope="col" class="text-end">Actions</th>
                    <% end %>
                  </tr>
                </thead>
                <tbody>
                  <% unless @factions.blank? %>
                    <% @factions.each do |faction| %>
                      <tr>
                        <td>
                          <div class="d-flex align-items-center">
                            <i class="bi bi-people fs-5 me-2 text-info"></i>
                            <strong><%= link_to faction.name, faction_path(faction, sector_id: @sector.id) %></strong>
                          </div>
                        </td>
                        <td><%= faction.description %></td>
                        <td class="text-center">
                          <i class="bi bi-flag-fill fs-4" style="color: <%= faction.color_code %>;" title="<%= faction.color_code %>"></i>
                        </td>
                        <td class="text-center text-muted small"><%= faction.created_at.strftime("%m/%d/%Y") %></td>
                        <td class="text-center text-muted small"><%= faction.updated_at.strftime("%m/%d/%Y") %></td>
                        <% if can_edit_factions?(@sector, current_user) %>
                          <td class="text-end">
                            <div class="btn-group" role="group">
                              <%= link_to edit_faction_path(faction, sector_model_faction: { sector_id: @sector.id }), class: 'btn btn-outline-secondary btn-sm', title: 'Edit' do %>
                                <i class="bi bi-pencil"></i>
                              <% end %>
                              <%= link_to faction_path(faction, sector_model_faction: { sector_id: @sector.id }), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-outline-danger btn-sm', title: 'Delete' do %>
                                <i class="bi bi-trash"></i>
                              <% end %>
                            </div>
                          </td>
                        <% end %>
                      </tr>
                    <% end %>
                  <% end %>
                </tbody>
              </table>
            </div>

            <div class="mt-3">
              <%= link_to sector_path(@sector), class: 'btn btn-secondary' do %>
                <i class="bi bi-arrow-left"></i> Back to Sector
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>

app/views/sector/factions/new.html.erb
<% content_for :page_title, 'New Faction' %>

<div class="container-fluid">
  <div class="pagetitle">
    <h1>New Faction</h1>
    <nav>
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/">Home</a></li>
        <li class="breadcrumb-item"><%= link_to "Sectors", sectors_path %></li>
        <li class="breadcrumb-item"><%= link_to @sector.name, sector_path(@sector) %></li>
        <li class="breadcrumb-item"><%= link_to "Factions", factions_path(sector_id: @sector.id) %></li>
        <li class="breadcrumb-item active">New</li>
      </ol>
    </nav>
  </div>

  <section class="section">
    <div class="row justify-content-center">
      <div class="col-lg-8">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">Create New Faction in <%= @sector.name %> Sector</h5>

            <%= form_for @faction, url: factions_path, html: { class: "row g-3" } do |f| %>
              <% if @faction.errors.any? %>
                <div class="col-12">
                  <div class="alert alert-danger alert-dismissible fade show" role="alert">
                    <h4 class="alert-heading"><%= pluralize(@faction.errors.count, "error") %> prohibited this faction from being saved:</h4>
                    <ul class="mb-0">
                      <% @faction.errors.full_messages.each do |message| %>
                        <li><%= message %></li>
                      <% end %>
                    </ul>
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                  </div>
                </div>
              <% end %>

              <%= f.hidden_field :sector_id, value: @sector.id %>
              <%= f.hidden_field :created_at, value: Time.now %>
              <%= f.hidden_field :updated_at, value: Time.now %>

              <div class="col-12">
                <%= f.label :name, class: "form-label" %>
                <%= f.text_field :name, class: 'form-control', placeholder: "Faction Name" %>
              </div>

              <div class="col-12">
                <%= f.label :description, class: "form-label" %>
                <%= f.text_area :description, class: 'form-control', rows: 3, placeholder: "Brief description of the faction" %>
              </div>

              <div class="col-12 mt-3">
                <%= f.label :color_code, "Faction Color", class: "form-label d-block" %>
                <%= f.text_field :color_code, id: 'color_picker', class: "form-control" %>
                <div class="form-text">Choose a color to represent this faction on the hexmap.</div>
              </div>

              <div class="text-center mt-4">
                <%= f.submit "Create Faction", class: 'btn btn-primary px-4' %>
                <%= link_to 'Cancel', factions_path(sector_id: @sector.id), class: "btn btn-secondary px-4" %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>

<script>
  $(document).ready(function() {
    $('#color_picker').spectrum({
      preferredFormat: "rgb",
      showInput: true
    });
  });
</script>

app/views/sector/factions/show.html.erb
<% content_for :page_title, "#{@faction.name} Faction" %>

<div class="container-fluid">
  <% unless @faction.blank? %>
    <div class="pagetitle">
      <h1><%= @faction.name %> Faction</h1>
      <nav>
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="/">Home</a></li>
          <li class="breadcrumb-item"><%= link_to "Sectors", sectors_path %></li>
          <li class="breadcrumb-item"><%= link_to @sector.name, sector_path(@sector) %></li>
          <li class="breadcrumb-item"><%= link_to "Factions", factions_path(sector_id: @sector.id) %></li>
          <li class="breadcrumb-item active"><%= @faction.name %></li>
        </ol>
      </nav>
    </div>

    <section class="section">
      <div class="row">
        <div class="col-lg-8">
          <div class="card">
            <div class="card-body">
              <div class="d-flex justify-content-between align-items-center mb-3">
                <h5 class="card-title">Faction Details</h5>
                <i class="bi bi-flag-fill fs-3" style="color: <%= @faction.color_code %>;" title="<%= @faction.color_code %>"></i>
              </div>

              <div class="row mb-3">
                <div class="col-lg-3 col-md-4 label fw-bold text-primary">Name</div>
                <div class="col-lg-9 col-md-8"><%= @faction.name %></div>
              </div>

              <div class="row mb-3">
                <div class="col-lg-3 col-md-4 label fw-bold text-primary">Description</div>
                <div class="col-lg-9 col-md-8"><%= @faction.description %></div>
              </div>

              <div class="row mb-3">
                <div class="col-lg-3 col-md-4 label fw-bold text-primary">Color Code</div>
                <div class="col-lg-9 col-md-8">
                  <code><%= @faction.color_code %></code>
                </div>
              </div>

              <div class="mt-4 pt-3 border-top">
                <div class="d-flex gap-2">
                  <% if can_edit_factions?(@sector, current_user) %>
                    <%= link_to edit_faction_path(@faction, sector_model_faction: { sector_id: @sector.id }), class: 'btn btn-primary' do %>
                      <i class="bi bi-pencil"></i> Edit Faction
                    <% end %>
                  <% end %>
                  <%= link_to factions_path(sector_id: @sector.id), class: 'btn btn-secondary' do %>
                    <i class="bi bi-arrow-left"></i> Back to Factions
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="col-lg-4">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title">Quick Actions</h5>
              <div class="list-group">
                <%= link_to sector_path(@sector), class: "list-group-item list-group-item-action" do %>
                  <i class="bi bi-globe me-2 text-primary"></i> Sector Details
                <% end %>
                <% if can_view_systems?(@sector, current_user) %>
                  <%= link_to systems_path(sector_id: @sector.id), class: "list-group-item list-group-item-action" do %>
                    <i class="bi bi-layers me-2 text-info"></i> View Systems
                  <% end %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  <% end %>
</div>