config/routes.rb
Rails.application.routes.draw do
  root 'index#landing_page'
  devise_for :users

  # Should move hexmap stuff into its own controller and use index as main landing pages... thinking about future expansion and such
  # Example single route for my goldfish like memory: get 'index/hexmap', to: 'index#hexmap'
  resources :index do
    collection do
      get 'landing_page'
    end
  end

  resources :hex_system do
    collection do
      get 'hexmap'
    end
  end

  resources :sectors, controller:'sector/sectors' do
    resources :permissions, controller: 'sector/permissions'
  end
  resources :systems, controller:'sector/systems' do
    collection do
      get 'bulk_upload'
      post 'process_bulk_upload'
    end
    member do
      patch 'update_allegiance'
    end
    resources :system_notes, controller: 'sector/system_notes'
  end
  resources :factions, controller:'sector/factions'
  resource :profile, only: [:show], controller: 'profiles'

  namespace :admin do
    resources :users do
      member do
        patch :reset_password
      end
    end
  end

end

app/models/sector_model/sector.rb
class SectorModel::Sector < ApplicationRecord
  self.table_name = 'sectors'
  has_many :systems, dependent: :destroy
  has_many :factions, dependent: :destroy
  has_many :sector_permissions, foreign_key: :sector_id, dependent: :destroy
  has_many :permitted_users, through: :sector_permissions, source: :user

  validates :border_width, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 20 }, allow_nil: true
  validates :border_opacity, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 1 }, allow_nil: true
  validates :grid_opacity, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 1 }, allow_nil: true
  validates :show_grid, inclusion: { in: [true, false] }, allow_nil: true
end

app/models/sector_model/system_note.rb
class SectorModel::SystemNote < ApplicationRecord
  belongs_to :system
  self.table_name = 'system_notes'
  
  validates :content, presence: true
  validates_length_of :content, minimum: 5, maximum: 512
  
end

app/controllers/sector/factions_controller.rb
class Sector::FactionsController < ApplicationController
  before_action :check_member, only: [:new, :edit, :update, :destroy]
  before_action :presets
   
  def index
    @sector = SectorModel::Sector.find(params[:sector_id])
    if can_view_factions?(@sector, current_user)
      @factions = SectorModel::Faction.where("sector_id = ?", params[:sector_id])
    else
      redirect_back_or_to sector_path(@sector), alert: "You do not have permission to view factions for this sector."
    end
  end

  def show
    @faction = SectorModel::Faction.find(params[:id])
    @sector = @faction.sector
    unless can_view_factions?(@sector, current_user)
      redirect_back_or_to sector_path(@sector), alert: "You do not have permission to view factions for this sector."
    end
  end

  def new
    @sector = SectorModel::Sector.find(params[:sector_id] || params.dig(:sector_model_faction, :sector_id))
    if can_edit_factions?(@sector, current_user)
      @faction = SectorModel::Faction.new
    else
      redirect_back_or_to factions_path(sector_id: @sector.id), alert: "You do not have permission to edit factions."
    end
  end

  def create
    @sector = SectorModel::Sector.find(params[:sector_id] || params.dig(:sector_model_faction, :sector_id))
    if can_edit_factions?(@sector, current_user)
      @faction = SectorModel::Faction.new(faction_params)
      @faction.sector = @sector

      if @faction.save
        respond_to do |format|
          format.html { redirect_to factions_path(sector_id: @sector.id) }
          format.json { render json: @faction, status: :created }
        end
      else
        respond_to do |format|
          format.html { render 'new' }
          format.json { render json: @faction.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_back_or_to factions_path(sector_id: @sector.id), alert: "You do not have permission to edit factions."
    end
  end

  def edit
    @sector = SectorModel::Sector.find(params[:sector_id] || params.dig(:sector_model_faction, :sector_id))
    @faction = SectorModel::Faction.find(params[:id])
    
    unless can_edit_factions?(@sector, current_user)
      redirect_back_or_to factions_path(sector_id: @sector.id), alert: "You do not have permission to edit factions."
    end
  end

  def update
    @sector = SectorModel::Sector.find(params[:sector_id] || params.dig(:sector_model_faction, :sector_id))
    @faction = SectorModel::Faction.find(params[:id])
    
    if can_edit_factions?(@sector, current_user)
      if @faction.update(faction_params)
        redirect_to factions_path(sector_id: @sector.id)
      else
        render 'edit'
      end
    else
      redirect_back_or_to factions_path(sector_id: @sector.id), alert: "You do not have permission to edit factions."
    end
    
  end

  def destroy
    @sector = SectorModel::Sector.find(params[:sector_id] || params[:sector_model_faction][:sector_id])
    @faction = SectorModel::Faction.find(params[:id])
    
    if can_edit_factions?(@sector, current_user)
      @faction.destroy
    else
      redirect_back_or_to factions_path(sector_id: @sector.id), alert: "You do not have permission to delete factions." and return
    end
    
    redirect_to factions_path(sector_id: @sector.id)
  end

  private

  def faction_params
    params.require(:sector_model_faction).permit(:sector_id, :name, :description, :color_code, :created_at, :updated_at)
  end

	def presets
		@page_libs = [:color_picker]
	end
	
end

app/controllers/sector/permissions_controller.rb
class Sector::PermissionsController < ApplicationController
  before_action :set_sector

  def index
    @permissions = @sector.sector_permissions.includes(:user)
  end

  def new
    @permission = @sector.sector_permissions.new
    @users = User.where.not(id: @sector.permitted_users.pluck(:id)).where.not(email: @sector.author)
  end

  def create
    @permission = @sector.sector_permissions.new(permission_params)
    if @permission.save
      redirect_to sector_permissions_path(@sector), notice: 'Permission added successfully.'
    else
      @users = User.where.not(id: @sector.permitted_users.pluck(:id)).where.not(email: @sector.author)
      render :new
    end
  end

  def edit
    @permission = @sector.sector_permissions.find(params[:id])
  end

  def update
    @permission = @sector.sector_permissions.find(params[:id])
    if @permission.update(permission_params)
      redirect_to sector_permissions_path(@sector), notice: 'Permission updated successfully.'
    else
      render :edit
    end
  end

  def destroy
    @permission = @sector.sector_permissions.find(params[:id])
    @permission.destroy
    redirect_to sector_permissions_path(@sector), notice: 'Permission removed successfully.'
  end

  private

  def set_sector
    @sector = SectorModel::Sector.find(params[:sector_id])
    unless @sector.author == current_user.email || current_user.admin?
      redirect_back_or_to sectors_path, alert: 'You do not have permission to manage permissions for this sector.'
    end
  end

  def permission_params
    params.require(:sector_permission).permit(:user_id, :can_view_sector, :can_edit_sector, :can_view_factions, :can_edit_factions, :can_view_systems, :can_edit_systems, :can_view_system_notes, :can_edit_system_notes)
  end
end

app/controllers/sector/sectors_controller.rb
class Sector::SectorsController < ApplicationController
  before_action :check_member, only: [:new, :edit, :update, :destroy]
  before_action :presets, only: [:new, :edit, :create, :update]
   
  def index
    @sectors = SectorModel::Sector.left_outer_joins(:sector_permissions)
                                  .where("sectors.public_view = '1' OR sectors.author = ? OR sector_permissions.user_id = ?", current_user.email, current_user.id)
                                  .distinct
    if current_user.admin?
      @sectors = SectorModel::Sector.all
    end
  end

  def show
    @sector = SectorModel::Sector.find(params[:id])
    unless can_view_sector?(@sector, current_user)
      redirect_back_or_to sectors_path, alert: "You do not have permission to view this sector."
    end
  end

  def new
    @sector = SectorModel::Sector.new
    gon.hex_color = "#f8f9fa"
    gon.border_width = 4
    gon.border_opacity = 0.5
    gon.background_image = nil
    gon.show_grid = true
    gon.grid_opacity = 0.1
    gon.background_images = Dir.glob(Rails.root.join('app', 'assets', 'images', 'backgrounds', '*.svg')).each_with_object({}) do |f, hash|
      filename = File.basename(f)
      hash[filename] = ActionController::Base.helpers.image_path("backgrounds/#{filename}")
    end
  end

  def create
    @sector = SectorModel::Sector.new(sector_params)

    if @sector.save
      redirect_to sectors_path
    else
      render 'new'
    end
  end

  def edit
    @sector = SectorModel::Sector.find(params[:id])
    
    unless can_edit_sector?(@sector, current_user)
      redirect_back_or_to sectors_path, alert: "You do not have permission to edit this sector."
    end

    gon.hex_color = @sector.hex_color.presence || "#f8f9fa"
    gon.border_width = @sector.border_width.presence || 4
    gon.border_opacity = @sector.border_opacity.presence || 0.5
    gon.background_image = @sector.background_image.presence
    gon.show_grid = @sector.show_grid
    gon.grid_opacity = @sector.grid_opacity.presence || 0.1
    gon.background_images = Dir.glob(Rails.root.join('app', 'assets', 'images', 'backgrounds', '*.svg')).each_with_object({}) do |f, hash|
      filename = File.basename(f)
      hash[filename] = ActionController::Base.helpers.image_path("backgrounds/#{filename}")
    end
  end

  def update
    @sector = SectorModel::Sector.find(params[:id])
    
    if can_edit_sector?(@sector, current_user)
      if @sector.update(sector_params)
        redirect_to sectors_path
      else
        render 'edit'
      end
    else
      redirect_back_or_to sectors_path, alert: "You do not have permission to edit this sector."
    end
    
  end

  def destroy
    @sector = SectorModel::Sector.find(params[:id])
    
    if @sector.author == current_user.email || current_user.admin?
      @sector.destroy
    else
      redirect_back_or_to sectors_path, alert: "Only the author can delete this sector." and return
    end
    
    redirect_to sectors_path
  end

  private

  def presets
    @page_libs = [:hexmap]
    
    # Sample data for hexmap preview
    @preview_data = {
      "0" => { n: "System A", q: 1, r: 1, hex_loc: "0101", allegiance: "Faction 1", colour: "#ff5733" },
      "1" => { n: "System B", q: 1, r: 2, hex_loc: "0102", allegiance: "Faction 1", colour: "#ff5733" },
      "2" => { n: "System C", q: 2, r: 1, hex_loc: "0201", allegiance: "Faction 2", colour: "#33ff57" },
      "3" => { n: "System D", q: 2, r: 2, hex_loc: "0202", allegiance: "Faction 2", colour: "#33ff57" }
    }
    gon.data = @preview_data
  end

  def sector_params
    params.require(:sector_model_sector).permit(:author, :name, :public_view, :hex_color, :border_width, :border_opacity, :background_image, :show_grid, :grid_opacity, :created_at, :updated_at)
  end

  # TODO: Add in ability to export an entire sector, its systems, notes, factions, and sector settings.
  #   This should be done in a way that it could later be reimported to recreate that sector.

end

app/controllers/sector/system_notes_controller.rb
class Sector::SystemNotesController < ApplicationController
  before_action :check_member, only: [:new, :edit, :update, :destroy]
   
  def index
    @system = SectorModel::System.find(params[:system_id])
    @sector = @system.sector
    
    @system_notes = visible_system_notes(@system, current_user)
    
    if can_view_systems?(@sector, current_user)
      if params[:partial] == "yes"
        render partial: 'sector/system_notes/system_notes'
      end
    else
      redirect_back_or_to system_path(@system), alert: "You do not have permission to view this system."
    end
  end

  def new
    @system = SectorModel::System.find(params[:system_id])
    @sector = @system.sector
    
    if can_edit_system_notes?(@sector, current_user)
      @system_note = SectorModel::SystemNote.new
      respond_to do |format|
        format.html
        format.js
      end
    else
      redirect_back_or_to system_path(@system), alert: "You do not have permission to edit system notes."
    end
  end

  def create
    @system = SectorModel::System.find(params[:system_id])
    @sector = @system.sector

    if can_edit_system_notes?(@sector, current_user)
      @system_note = SectorModel::SystemNote.new(system_note_params)
      @system_note.system_id = @system.id
      if @system_note.save
        respond_to do |format|
          format.html { redirect_to system_path(@system) }
          format.js { head :no_content }
        end
      else
        respond_to do |format|
          format.html { render 'new' }
          format.js { render partial: 'form', locals: { errors: @system_note.errors }, status: :unprocessable_entity }
        end
      end
    else
      redirect_back_or_to system_path(@system), alert: "You do not have permission to edit system notes."
    end
  end

  def edit
    @system_note = SectorModel::SystemNote.find(params[:id])
    @system = SectorModel::System.find(params[:system_id])
    @sector = @system.sector
    
    unless can_edit_system_notes?(@sector, current_user) && (@system_note.author == current_user.email || @sector.author == current_user.email || current_user.admin?)
      redirect_back_or_to system_path(@system.id), alert: "You do not have permission to edit this system note."
    end

    respond_to do |format|
      format.html
      format.js
    end
  end

  def update
    @system_note = SectorModel::SystemNote.find(params[:id])
    @system = SectorModel::System.find(params[:system_id])
    @sector = @system.sector
    
    if can_edit_system_notes?(@sector, current_user) && (@system_note.author == current_user.email || @sector.author == current_user.email || current_user.admin?)
      if @system_note.update(system_note_params)
        respond_to do |format|
          format.html { redirect_to system_path(@system) }
          format.js { head :no_content }
        end
      else
        respond_to do |format|
          format.html { render 'edit' }
          format.js { render partial: 'form', locals: { errors: @system_note.errors }, status: :unprocessable_entity }
        end
      end
    else
      redirect_back_or_to system_path(@system.id), alert: "You do not have permission to edit this system note."
    end
    
  end

  def destroy
    @system_note = SectorModel::SystemNote.find(params[:id])
    @system = SectorModel::System.find(params[:system_id])
    @sector = @system.sector
    
    if can_edit_system_notes?(@sector, current_user) && (@system_note.author == current_user.email || @sector.author == current_user.email || current_user.admin?)
      @system_note.destroy
    else
      redirect_back_or_to system_path(@system.id), alert: "You do not have permission to delete this system note." and return
    end
    
    redirect_to system_path(@system.id)
  end

  private

  def system_note_params
    params.require(:sector_model_system_note).permit(:system_id, :author, :content, :public_view, :created_at, :updated_at)
  end
  
end

app/helpers/sector/sectors_helper.rb
module Sector::SectorsHelper
end

app/helpers/sector/systems_helper.rb
module Sector::SystemsHelper
  def combine_uwp_params(params)
    "#{params[:starport]}#{params[:planet_size]}#{params[:atmosphere]}#{params[:hydrosphere]}#{params[:population]}#{params[:goverment]}#{params[:law]}-#{params[:tech_level]}"
  end
  
  def combine_note_params(params)
    "#{params[:notes1]} #{params[:notes2]} #{params[:notes3]}".rstrip
  end

  def combine_pbg_params(params)
    "#{params[:pop_base]}#{params[:asteroid_belts]}#{params[:gas_giants]}" 
  end
  
end

app/helpers/system_notes_helper.rb
module SystemNotesHelper
end

app/views/sector/system_notes/_form.html.erb
<%= form_for @system_note, url: @system_note.persisted? ? system_system_note_path(system_id: @system.id, id: @system_note.id) : system_system_notes_path(system_id: @system.id), html: {class: "form_for_notes"} do |f| %>

  <% if @system_note.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@system_note.errors.count, "error") %> prohibited this note from being saved:
      </h2>
      <ul>
        <% @system_note.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

      <div class='col-lg-12'>
        <div class='card'>
          <div class='card-body'>
            <h5 class='card-title'>
              Note for <%= @system.name %> system
              <%= f.hidden_field :system_id, value: @system.id %>
              <%= f.hidden_field :author, value: current_user.email %>
            </h5>
          <div>

          <div class="form-group form_input_padding">
            <%= f.label :content %>
            <%= f.text_area :content, class: 'form-control', style:"height: 100px" %>
            <span class="pull-right label label-default" id="count_message"></span>
          </div>

          <div class="form_input_padding">
            <div class="form-check form-switch">
              <%= f.label :public_view, class: "form-check-label" %>
              <%= f.check_box :public_view, class: 'form-check-input' %>
            </div>
          </div>
          
          <%= f.hidden_field :updated_at, value: @system_note.persisted? ? Time.now : nil %>
          <%= f.hidden_field :created_at, value: Time.now %>  
          
          <div class='col-12 form_input_padding'><%= f.submit class: 'btn btn-primary' %></div>
          </div>            
          </div>
        </div>
      </div>

<% end %>

<script>
  $(document).ready(function() {
    var text_max = 512;
    $('#count_message').html('0 / ' + text_max );
    
    $('#sector_model_system_note_content').keyup(function() {
      var text_length = $('#sector_model_system_note_content').val().length;
      var text_remaining = text_max - text_length;
      
      $('#count_message').html(text_length + ' / ' + text_max);
    });
  });
</script>

app/views/sector/system_notes/_system_notes.html.erb
  <div class="pagetitle">
    <h1>Notes <span>| 
    <% if can_edit_system_notes?(@sector, current_user) %>
      <button class='btn btn-primary btn-sm open-modal-click' id="new_note">New Note</button>
    <% end %></span></h1>
  </div>
  
  <% @system_notes.each do |note| %>
    <div class="col-12">
      <div class="card overflow-auto" style="min-height: 50px;">
        <div class="card-body">
          <h5 class="card-title"><%= note.author.split('@').first %> <span>| <small><%= note.updated_at.strftime("%m/%d/%Y") %></small></span></h5>
          <%= note.content %>
          <% if can_edit_system_notes?(@sector, current_user) && (note.author == current_user.email || @sector.author == current_user.email || current_user.admin?) %>
            <div class="pt-3">
              <button class='btn btn-warning open-modal-click' id="edit_note" data-url="<%= edit_system_system_note_path(system_id: @system.id, id: note.id) %>">Edit</button>
              <%= link_to 'Delete', system_system_note_path(system_id: @system.id, id: note.id), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>                        
            </div>
          <% end %>          
        </div>
      </div>
    </div>
  <% end %>

  <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="myModalLabel"></h4>
        </div>
        <div class="modal-body">
          <div id="modal-content"></div>
        </div>
      </div>
    </div>
  </div>
  
<script>

  $(document).ready(function() {
    $(".open-modal-click").click(function(event) {
      var clicked = $(this);
      var target = "";

      if (clicked.attr("id") == "new_note") {
        target = "<%= j new_system_system_note_path(system_id: @system.id) %>"
      } else if (clicked.attr("id") == "edit_note") {
        target = clicked.data("url")
      }
  
      $.ajax({
        url: target,
        type: "GET",
        dataType: "script",
        success: function(data) {
          $("#modal-content").html(data);
        }
      });
    });
  });

  $(document).off('submit', 'form.form_for_notes').on('submit', 'form.form_for_notes', function(event) {
    event.preventDefault();
    var form = $(this);
    $.ajax({
      url: form.attr('action'),
      type: form.attr('method'),
      data: form.serialize(),
      dataType: 'script',
      success: function(data, textStatus, xhr) {
        if (xhr.status === 204 || xhr.status === 200) {
          closeSystemNotesModal();

          $('.modal-content').html('');
          $.ajax({
            url: '<%= system_system_notes_path(system_id: @system.id, partial: "yes") %>',
            type: 'GET',
            success: function(data) {
              $('#notes_table').html(data);
            }
          });
        }
      },
      error: function(xhr) {
        $('.modal-content').html(xhr.responseText);
        $('#myModal').show();
      },
    });
  });

  function closeSystemNotesModal() {
      var modalElement = document.getElementById('myModal');
      
      // Use Bootstrap 5 API explicitly
      if (window.bootstrap && bootstrap.Modal) {
          var modal = bootstrap.Modal.getInstance(modalElement);
          if (!modal) {
              modal = new bootstrap.Modal(modalElement);
          }
          modal.hide();
      } else if (typeof $(modalElement).modal === 'function') {
          $(modalElement).modal('hide');
      }

      // Fallback if bootstrap modal doesn't close properly
      setTimeout(function() {
        if ($('.modal-backdrop').length > 0) {
          $('.modal-backdrop').remove();
          $('body').removeClass('modal-open');
          $('body').css('overflow', '');
          $('body').css('padding-right', '');
        }
      }, 500);
  }

</script>

app/views/sector/system_notes/edit.html.erb
<% content_for :page_title, 'Edit Note' %>

<%= form_with model: @system_note, url: system_note_path(@system_note), method: :patch do |f| %>

  <% if @system_note.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@system_note.errors.count, "error") %> prohibited this note from being saved:
      </h2>
      <ul>
        <% @system_note.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="pagetitle">
    <h1>New Note</h1>
    <nav>
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/">Home</a></li>
        <li class="breadcrumb-item"><%= link_to "Sectors", sectors_path %></li>
        <li class="breadcrumb-item active"><%= link_to @system.name, system_notes_path(system_id: @system.id) %></li>
      </ol>
    </nav>
  </div>
  
  <section class='section'>
    <div class='row'>
      <div class='col-lg-10'>
        <div class='card'>
          <div class='card-body'>
            <h5 class='card-title'>
              Note located in: <%= @system.name %> system
              <%= f.hidden_field :system_id, value: @system.id %>
            </h5>
            <div>
              
            <div class="form-group form_input_padding">
              <%= f.label :content %>
              <%= f.text_field :content, class: 'form-control' %>
            </div>

            <div class="form_input_padding">
              <div class="form-check form-switch">
                <%= f.label :public_view, class: "form-check-label" %>
                <%= f.check_box :public_view, class: 'form-check-input' %>
              </div>
            </div>
            
            <%= f.hidden_field :updated_at, value: Time.now %>
            
            <div class='col-12 form_input_padding'><%= f.submit class: 'btn btn-primary' %></div>
            </div>            
          </div>
        </div>
      </div>
    </div>
  </section>
  
<% end %>

app/views/sector/system_notes/edit.js.erb
$('.modal-content').html("<%= j render partial: 'form' %>");
$('#myModal').modal('show');

app/views/sector/system_notes/index.html.erb
<% content_for :page_title, 'Notes' %>

<div class="pagetitle">
  <h1>Notes</h1>
  <nav>
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="/">Home</a></li>
      <li class="breadcrumb-item"><%= link_to "System", systems_path %></li>
    </ol>
  </nav>
</div>

<section>
  <div class="col-12">
    <div class="card overflow-auto">
      <div class="card-body">
        <h5 class="card-title">Notes <span>| <button class='btn btn-primary btn-sm' id="new_note">New Note</button></span></h5>
        <table class="table table-borderless table-sm table-striped">
          <thead>
            <tr>
              <th>Author</th>
              <th>Content</th>
              <th>Created Date</th>
              <th>Last Updated</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            <% unless @system_notes.blank? %>
              <% @system_notes.each do |note| %>
                <% if note.author == current_user.email || note.public_view == '1' || current_user.admin? %>
                  <tr>
                    <td><%= note.author.split('@').first %></td>
                    <td><%= note.content %></td>
                    <td><%= note.created_at.strftime("%m/%d/%Y") %></td>
                    <td><%= note.updated_at.strftime("%m/%d/%Y") %></td>
                    <td>
                      <% unless note.author != current_user.email %>
                        <div class="btn-group">
                          <%= link_to 'Edit', edit_system_note_path(note, sector_model_system_note: { system_id: @system.id }), class: "btn btn-warning" %>
                          <%= link_to 'Delete', system_note_path(note, sector_model_system_note: { system_id: @system.id }), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>                        
                        </div>
                      <% end %>
                    </td>
                  </tr>
                <% end %>
              <% end %>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</section>

app/views/sector/system_notes/new.html.erb
<%= form_for @system_note, url: system_notes_path do |f| %>

  <% if @system_note.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@system_note.errors.count, "error") %> prohibited this note from being saved:
      </h2>
      <ul>
        <% @system_note.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="pagetitle">
    <h1>New Note</h1>
    <nav>
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/">Home</a></li>
        <li class="breadcrumb-item"><%= link_to "Sectors", sectors_path %></li>
        <li class="breadcrumb-item active"><%= link_to @system.name, system_notes_path(system_id: @system.id) %></li>
      </ol>
    </nav>
  </div>
  
  <section class='section'>
    <div class='row'>
      <div class='col-lg-10'>
        <div class='card'>
          <div class='card-body'>
            <h5 class='card-title'>
              Note for <%= @system.name %> system
              <%= f.hidden_field :system_id, value: @system.id %>
              <%= f.hidden_field :author, value: current_user.email %>
            </h5>
          <div>

          <div class="form-group form_input_padding">
            <%= f.label :content %>
            <%= f.text_field :content, class: 'form-control' %>
          </div>

          <div class="form_input_padding">
            <div class="form-check form-switch">
              <%= f.label :public_view, class: "form-check-label" %>
              <%= f.check_box :public_view, class: 'form-check-input' %>
            </div>
          </div>
            
          <%= f.hidden_field :updated_at, value: Time.now %>
          <%= f.hidden_field :created_at, value: Time.now %>  
          
          <div class='col-12 form_input_padding'><%= f.submit class: 'btn btn-primary' %></div>
          </div>            
          </div>
        </div>
      </div>
    </div>
  </section>
  
<% end %>

app/views/sector/system_notes/new.js.erb
$('.modal-content').html("<%= j render partial: 'form' %>");
$('#myModal').modal('show');

app/views/sector/system_notes/show.html.erb
<% content_for :page_title, 'Faction' %>

<% unless @faction.blank? %>
  <div class="pagetitle">
    <h1><%= @faction.name %> Faction</h1>
    <nav>
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/">Home</a></li>
        <li class="breadcrumb-item"><%= link_to "Sectors", sectors_path %></li>
        <li class="breadcrumb-item active"><%= link_to @sector.name, factions_path(sector_id: @sector.id) %></li>
      </ol>
    </nav>
  </div>
  
  <section>
    <div class="card">
      <p><strong>Name: </strong><%= @faction.name %></p>
      <p><strong>Description: </strong><%= @faction.description %></p>
      <p><strong>Color Code: </strong> <%= @faction.color_code %></p>
    </div>
  </section>
<% end %>