config/routes.rb
Rails.application.routes.draw do
  root 'index#landing_page'
  devise_for :users

  # Should move hexmap stuff into its own controller and use index as main landing pages... thinking about future expansion and such
  # Example single route for my goldfish like memory: get 'index/hexmap', to: 'index#hexmap'
  resources :index do
    collection do
      get 'landing_page'
    end
  end

  resources :hex_system do
    collection do
      get 'hexmap'
    end
  end

  resources :sectors, controller:'sector/sectors' do
    resources :permissions, controller: 'sector/permissions'
  end
  resources :systems, controller:'sector/systems' do
    collection do
      get 'bulk_upload'
      post 'process_bulk_upload'
    end
    member do
      patch 'update_allegiance'
    end
    resources :system_notes, controller: 'sector/system_notes'
  end
  resources :factions, controller:'sector/factions'
  resource :profile, only: [:show], controller: 'profiles'

  namespace :admin do
    resources :users do
      member do
        patch :reset_password
      end
    end
  end

end

app/models/sector_model/sector.rb
class SectorModel::Sector < ApplicationRecord
  self.table_name = 'sectors'
  has_many :systems, dependent: :destroy
  has_many :factions, dependent: :destroy
  has_many :sector_permissions, foreign_key: :sector_id, dependent: :destroy
  has_many :permitted_users, through: :sector_permissions, source: :user

  validates :border_width, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 20 }, allow_nil: true
  validates :border_opacity, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 1 }, allow_nil: true
  validates :grid_opacity, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 1 }, allow_nil: true
  validates :show_grid, inclusion: { in: [true, false] }, allow_nil: true
end

app/models/system.rb
class System < ApplicationRecord
  include Shared::SystemMapping
  self.table_name = 'traveller_systems.systems'

  # Start of methods to convert UWP codes into human readable attributes.
  def starport
    PORT_MAP[self.uwp[0]] if PORT_MAP.key?(self.uwp[0])
  end
  
  def planet_size
    SIZE_MAP[self.uwp[1]] if SIZE_MAP.key?(self.uwp[1])
  end
  
  def atmosphere
    ATMO_MAP[self.uwp[2]] if ATMO_MAP.key?(self.uwp[2])
  end
  
  def hydrosphere
    HYDRO_MAP[self.uwp[3]] if HYDRO_MAP.key?(self.uwp[3])
  end
  
  def population
    POP_MAP[self.uwp[4]].call(self.pbg) if POP_MAP.key?(self.uwp[4])
  end
  
  def goverment
    GOV_MAP[self.uwp[5]] if GOV_MAP.key?(self.uwp[5])
  end
  
  def law
    LAW_MAP[self.uwp[6]] if LAW_MAP.key?(self.uwp[6])
  end
  
  def tech_level
    TECH_MAP[self.uwp[8]] if TECH_MAP.key?(self.uwp[8])
  end
  
  def bases
    BASES_MAP[self.base[0]] if BASES_MAP.key?(self.base[0])
  end

  def notes1
    NOTES_MAP[self.notes[0,2]] if NOTES_MAP.key?(self.notes[0,2])
  end

  def notes2
    NOTES_MAP[self.notes[3,2]] if NOTES_MAP.key?(self.notes[3,2])
  end

  def notes3
    NOTES_MAP[self.notes[6,2]] if NOTES_MAP.key?(self.notes[6,2])
  end
  
  def advisory
    ADVISORY_MAP[self.ring[0]] if ADVISORY_MAP.key?(self.ring[0])
  end
  
  def asteroid_belts
    self.pbg[1]
  end
  
  def gas_giants
    self.pbg[2]
  end

  def self.hexmap
    select("location, name, SUM(SUBSTRING(location, 1, 2)) AS q, SUM(SUBSTRING(location, 3, 2) - 41) * -1 AS r")
    .group(:location)
  end

end

app/controllers/sector/factions_controller.rb
class Sector::FactionsController < ApplicationController
  before_action :check_member, only: [:new, :edit, :update, :destroy]
  before_action :presets
   
  def index
    @sector = SectorModel::Sector.find(params[:sector_id])
    if can_view_factions?(@sector, current_user)
      @factions = SectorModel::Faction.where("sector_id = ?", params[:sector_id])
    else
      redirect_back_or_to sector_path(@sector), alert: "You do not have permission to view factions for this sector."
    end
  end

  def show
    @faction = SectorModel::Faction.find(params[:id])
    @sector = @faction.sector
    unless can_view_factions?(@sector, current_user)
      redirect_back_or_to sector_path(@sector), alert: "You do not have permission to view factions for this sector."
    end
  end

  def new
    @sector = SectorModel::Sector.find(params[:sector_id] || params.dig(:sector_model_faction, :sector_id))
    if can_edit_factions?(@sector, current_user)
      @faction = SectorModel::Faction.new
    else
      redirect_back_or_to factions_path(sector_id: @sector.id), alert: "You do not have permission to edit factions."
    end
  end

  def create
    @sector = SectorModel::Sector.find(params[:sector_id] || params.dig(:sector_model_faction, :sector_id))
    if can_edit_factions?(@sector, current_user)
      @faction = SectorModel::Faction.new(faction_params)
      @faction.sector = @sector

      if @faction.save
        respond_to do |format|
          format.html { redirect_to factions_path(sector_id: @sector.id) }
          format.json { render json: @faction, status: :created }
        end
      else
        respond_to do |format|
          format.html { render 'new' }
          format.json { render json: @faction.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_back_or_to factions_path(sector_id: @sector.id), alert: "You do not have permission to edit factions."
    end
  end

  def edit
    @sector = SectorModel::Sector.find(params[:sector_id] || params.dig(:sector_model_faction, :sector_id))
    @faction = SectorModel::Faction.find(params[:id])
    
    unless can_edit_factions?(@sector, current_user)
      redirect_back_or_to factions_path(sector_id: @sector.id), alert: "You do not have permission to edit factions."
    end
  end

  def update
    @sector = SectorModel::Sector.find(params[:sector_id] || params.dig(:sector_model_faction, :sector_id))
    @faction = SectorModel::Faction.find(params[:id])
    
    if can_edit_factions?(@sector, current_user)
      if @faction.update(faction_params)
        redirect_to factions_path(sector_id: @sector.id)
      else
        render 'edit'
      end
    else
      redirect_back_or_to factions_path(sector_id: @sector.id), alert: "You do not have permission to edit factions."
    end
    
  end

  def destroy
    @sector = SectorModel::Sector.find(params[:sector_id] || params[:sector_model_faction][:sector_id])
    @faction = SectorModel::Faction.find(params[:id])
    
    if can_edit_factions?(@sector, current_user)
      @faction.destroy
    else
      redirect_back_or_to factions_path(sector_id: @sector.id), alert: "You do not have permission to delete factions." and return
    end
    
    redirect_to factions_path(sector_id: @sector.id)
  end

  private

  def faction_params
    params.require(:sector_model_faction).permit(:sector_id, :name, :description, :color_code, :created_at, :updated_at)
  end

	def presets
		@page_libs = [:color_picker]
	end
	
end

app/controllers/sector/permissions_controller.rb
class Sector::PermissionsController < ApplicationController
  before_action :set_sector

  def index
    @permissions = @sector.sector_permissions.includes(:user)
  end

  def new
    @permission = @sector.sector_permissions.new
    @users = User.where.not(id: @sector.permitted_users.pluck(:id)).where.not(email: @sector.author)
  end

  def create
    @permission = @sector.sector_permissions.new(permission_params)
    if @permission.save
      redirect_to sector_permissions_path(@sector), notice: 'Permission added successfully.'
    else
      @users = User.where.not(id: @sector.permitted_users.pluck(:id)).where.not(email: @sector.author)
      render :new
    end
  end

  def edit
    @permission = @sector.sector_permissions.find(params[:id])
  end

  def update
    @permission = @sector.sector_permissions.find(params[:id])
    if @permission.update(permission_params)
      redirect_to sector_permissions_path(@sector), notice: 'Permission updated successfully.'
    else
      render :edit
    end
  end

  def destroy
    @permission = @sector.sector_permissions.find(params[:id])
    @permission.destroy
    redirect_to sector_permissions_path(@sector), notice: 'Permission removed successfully.'
  end

  private

  def set_sector
    @sector = SectorModel::Sector.find(params[:sector_id])
    unless @sector.author == current_user.email || current_user.admin?
      redirect_back_or_to sectors_path, alert: 'You do not have permission to manage permissions for this sector.'
    end
  end

  def permission_params
    params.require(:sector_permission).permit(:user_id, :can_view_sector, :can_edit_sector, :can_view_factions, :can_edit_factions, :can_view_systems, :can_edit_systems, :can_view_system_notes, :can_edit_system_notes)
  end
end

app/controllers/sector/sectors_controller.rb
class Sector::SectorsController < ApplicationController
  before_action :check_member, only: [:new, :edit, :update, :destroy]
  before_action :presets, only: [:new, :edit, :create, :update]
   
  def index
    @sectors = SectorModel::Sector.left_outer_joins(:sector_permissions)
                                  .where("sectors.public_view = '1' OR sectors.author = ? OR sector_permissions.user_id = ?", current_user.email, current_user.id)
                                  .distinct
    if current_user.admin?
      @sectors = SectorModel::Sector.all
    end
  end

  def show
    @sector = SectorModel::Sector.find(params[:id])
    unless can_view_sector?(@sector, current_user)
      redirect_back_or_to sectors_path, alert: "You do not have permission to view this sector."
    end
  end

  def new
    @sector = SectorModel::Sector.new
    gon.hex_color = "#f8f9fa"
    gon.border_width = 4
    gon.border_opacity = 0.5
    gon.background_image = nil
    gon.show_grid = true
    gon.grid_opacity = 0.1
    gon.background_images = Dir.glob(Rails.root.join('app', 'assets', 'images', 'backgrounds', '*.svg')).each_with_object({}) do |f, hash|
      filename = File.basename(f)
      hash[filename] = ActionController::Base.helpers.image_path("backgrounds/#{filename}")
    end
  end

  def create
    @sector = SectorModel::Sector.new(sector_params)

    if @sector.save
      redirect_to sectors_path
    else
      render 'new'
    end
  end

  def edit
    @sector = SectorModel::Sector.find(params[:id])
    
    unless can_edit_sector?(@sector, current_user)
      redirect_back_or_to sectors_path, alert: "You do not have permission to edit this sector."
    end

    gon.hex_color = @sector.hex_color.presence || "#f8f9fa"
    gon.border_width = @sector.border_width.presence || 4
    gon.border_opacity = @sector.border_opacity.presence || 0.5
    gon.background_image = @sector.background_image.presence
    gon.show_grid = @sector.show_grid
    gon.grid_opacity = @sector.grid_opacity.presence || 0.1
    gon.background_images = Dir.glob(Rails.root.join('app', 'assets', 'images', 'backgrounds', '*.svg')).each_with_object({}) do |f, hash|
      filename = File.basename(f)
      hash[filename] = ActionController::Base.helpers.image_path("backgrounds/#{filename}")
    end
  end

  def update
    @sector = SectorModel::Sector.find(params[:id])
    
    if can_edit_sector?(@sector, current_user)
      if @sector.update(sector_params)
        redirect_to sectors_path
      else
        render 'edit'
      end
    else
      redirect_back_or_to sectors_path, alert: "You do not have permission to edit this sector."
    end
    
  end

  def destroy
    @sector = SectorModel::Sector.find(params[:id])
    
    if @sector.author == current_user.email || current_user.admin?
      @sector.destroy
    else
      redirect_back_or_to sectors_path, alert: "Only the author can delete this sector." and return
    end
    
    redirect_to sectors_path
  end

  private

  def presets
    @page_libs = [:hexmap]
    
    # Sample data for hexmap preview
    @preview_data = {
      "0" => { n: "System A", q: 1, r: 1, hex_loc: "0101", allegiance: "Faction 1", colour: "#ff5733" },
      "1" => { n: "System B", q: 1, r: 2, hex_loc: "0102", allegiance: "Faction 1", colour: "#ff5733" },
      "2" => { n: "System C", q: 2, r: 1, hex_loc: "0201", allegiance: "Faction 2", colour: "#33ff57" },
      "3" => { n: "System D", q: 2, r: 2, hex_loc: "0202", allegiance: "Faction 2", colour: "#33ff57" }
    }
    gon.data = @preview_data
  end

  def sector_params
    params.require(:sector_model_sector).permit(:author, :name, :public_view, :hex_color, :border_width, :border_opacity, :background_image, :show_grid, :grid_opacity, :created_at, :updated_at)
  end

  # TODO: Add in ability to export an entire sector, its systems, notes, factions, and sector settings.
  #   This should be done in a way that it could later be reimported to recreate that sector.

end

app/controllers/sector/system_notes_controller.rb
class Sector::SystemNotesController < ApplicationController
  before_action :check_member, only: [:new, :edit, :update, :destroy]
   
  def index
    @system = SectorModel::System.find(params[:system_id])
    @sector = @system.sector
    
    @system_notes = visible_system_notes(@system, current_user)
    
    if can_view_systems?(@sector, current_user)
      if params[:partial] == "yes"
        render partial: 'sector/system_notes/system_notes'
      end
    else
      redirect_back_or_to system_path(@system), alert: "You do not have permission to view this system."
    end
  end

  def new
    @system = SectorModel::System.find(params[:system_id])
    @sector = @system.sector
    
    if can_edit_system_notes?(@sector, current_user)
      @system_note = SectorModel::SystemNote.new
      respond_to do |format|
        format.html
        format.js
      end
    else
      redirect_back_or_to system_path(@system), alert: "You do not have permission to edit system notes."
    end
  end

  def create
    @system = SectorModel::System.find(params[:system_id])
    @sector = @system.sector

    if can_edit_system_notes?(@sector, current_user)
      @system_note = SectorModel::SystemNote.new(system_note_params)
      @system_note.system_id = @system.id
      if @system_note.save
        respond_to do |format|
          format.html { redirect_to system_path(@system) }
          format.js { head :no_content }
        end
      else
        respond_to do |format|
          format.html { render 'new' }
          format.js { render partial: 'form', locals: { errors: @system_note.errors }, status: :unprocessable_entity }
        end
      end
    else
      redirect_back_or_to system_path(@system), alert: "You do not have permission to edit system notes."
    end
  end

  def edit
    @system_note = SectorModel::SystemNote.find(params[:id])
    @system = SectorModel::System.find(params[:system_id])
    @sector = @system.sector
    
    unless can_edit_system_notes?(@sector, current_user) && (@system_note.author == current_user.email || @sector.author == current_user.email || current_user.admin?)
      redirect_back_or_to system_path(@system.id), alert: "You do not have permission to edit this system note."
    end

    respond_to do |format|
      format.html
      format.js
    end
  end

  def update
    @system_note = SectorModel::SystemNote.find(params[:id])
    @system = SectorModel::System.find(params[:system_id])
    @sector = @system.sector
    
    if can_edit_system_notes?(@sector, current_user) && (@system_note.author == current_user.email || @sector.author == current_user.email || current_user.admin?)
      if @system_note.update(system_note_params)
        respond_to do |format|
          format.html { redirect_to system_path(@system) }
          format.js { head :no_content }
        end
      else
        respond_to do |format|
          format.html { render 'edit' }
          format.js { render partial: 'form', locals: { errors: @system_note.errors }, status: :unprocessable_entity }
        end
      end
    else
      redirect_back_or_to system_path(@system.id), alert: "You do not have permission to edit this system note."
    end
    
  end

  def destroy
    @system_note = SectorModel::SystemNote.find(params[:id])
    @system = SectorModel::System.find(params[:system_id])
    @sector = @system.sector
    
    if can_edit_system_notes?(@sector, current_user) && (@system_note.author == current_user.email || @sector.author == current_user.email || current_user.admin?)
      @system_note.destroy
    else
      redirect_back_or_to system_path(@system.id), alert: "You do not have permission to delete this system note." and return
    end
    
    redirect_to system_path(@system.id)
  end

  private

  def system_note_params
    params.require(:sector_model_system_note).permit(:system_id, :author, :content, :public_view, :created_at, :updated_at)
  end
  
end

app/helpers/sector/sectors_helper.rb
module Sector::SectorsHelper
end

app/helpers/sector/systems_helper.rb
module Sector::SystemsHelper
  def combine_uwp_params(params)
    "#{params[:starport]}#{params[:planet_size]}#{params[:atmosphere]}#{params[:hydrosphere]}#{params[:population]}#{params[:goverment]}#{params[:law]}-#{params[:tech_level]}"
  end
  
  def combine_note_params(params)
    "#{params[:notes1]} #{params[:notes2]} #{params[:notes3]}".rstrip
  end

  def combine_pbg_params(params)
    "#{params[:pop_base]}#{params[:asteroid_belts]}#{params[:gas_giants]}" 
  end
  
end

app/views/sector/systems/bulk_upload.html.erb
<div class="container-fluid">
  <div class="pagetitle">
    <h1>Bulk Upload Systems</h1>
    <nav>
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/">Home</a></li>
        <li class="breadcrumb-item"><%= link_to "Sectors", sectors_path %></li>
        <li class="breadcrumb-item"><%= link_to @sector.name, sector_path(@sector) %></li>
        <li class="breadcrumb-item"><%= link_to "Systems", systems_path(sector_id: @sector.id) %></li>
        <li class="breadcrumb-item active">Bulk Upload</li>
      </ol>
    </nav>
  </div>

  <section class="section">
    <div class="row">
      <div class="col-lg-12">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">Upload Excel File</h5>

            <%= form_with(url: process_bulk_upload_systems_path, method: :post, local: true, multipart: true, class: "row g-3") do |f| %>
              <%= f.hidden_field :sector_id, value: @sector.id %>
              
              <div class="col-12">
                <label for="file" class="form-label">System File (.xlsx)</label>
                <%= f.file_field :file, class: "form-control", accept: ".xlsx" %>
              </div>

              <div class="col-12 mt-4">
                <%= f.submit "Upload and Process", class: "btn btn-primary" %>
                <%= link_to 'Cancel', systems_path(sector_id: @sector.id), class: "btn btn-secondary" %>
              </div>
            <% end %>

            <div class="alert alert-info mt-4">
              <h5 class="alert-heading"><i class="bi bi-info-circle me-2"></i>File Format Guidelines</h5>
              <p>The file should be an Excel (.xlsx) file with data starting from the first row (no headers).</p>
              <hr>
              <div class="row">
                <div class="col-md-6">
                  <ul class="mb-0">
                    <li><strong>Column A:</strong> System Name</li>
                    <li><strong>Column B:</strong> Location (e.g., 102 or 0102)</li>
                    <li><strong>Column C:</strong> UWP Code (e.g., E9A5686-1)</li>
                    <li><strong>Column D:</strong> Base Code (e.g., S, N, 2)</li>
                    <li><strong>Column E:</strong> Note 1 (e.g., Ag, Ni, etc.)</li>
                  </ul>
                </div>
                <div class="col-md-6">
                  <ul class="mb-0">
                    <li><strong>Column F:</strong> Note 2</li>
                    <li><strong>Column G:</strong> Ring/Advisory Code (e.g., A, R)</li>
                    <li><strong>Column H:</strong> PBG Code (3-digit number)</li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>

app/views/sector/systems/edit.html.erb
<div class="container-fluid">
  <div class="pagetitle">
    <h1>Edit System</h1>
    <nav>
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/">Home</a></li>
        <li class="breadcrumb-item"><%= link_to "Sectors", sectors_path %></li>
        <li class="breadcrumb-item"><%= link_to @sector.name, sector_path(@sector) %></li>
        <li class="breadcrumb-item"><%= link_to "Systems", systems_path(sector_id: @sector.id) %></li>
        <li class="breadcrumb-item"><%= link_to @system.name, system_path(@system) %></li>
        <li class="breadcrumb-item active">Edit</li>
      </ol>
    </nav>
  </div>

  <section class="section">
    <div class="row justify-content-center">
      <div class="col-lg-10">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">Update System Settings</h5>
            <%= render 'form' %>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>

app/views/sector/systems/index.html.erb
<% content_for :page_title, 'Systems' %>

<div class="container-fluid">
  <div class="pagetitle">
    <h1>Systems</h1>
    <nav>
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/">Home</a></li>
        <li class="breadcrumb-item"><%= link_to "Sectors", sectors_path %></li>
        <li class="breadcrumb-item"><%= link_to @sector.name, sector_path(@sector) %></li>
        <li class="breadcrumb-item active">Systems</li>
      </ol>
    </nav>
  </div>

  <section class="section">
    <div class="row">
      <div class="col-lg-12">
        <div class="card overflow-auto">
          <div class="card-body">
            <div class="d-flex justify-content-between align-items-center mb-3">
              <h5 class="card-title">Systems for <%= @sector.name %></h5>
              <div class="btn-group">
                <%= link_to "/hex_system/hexmap?sector_id=#{@sector.id}", class: "btn btn-outline-info" do %>
                  <i class="bi bi-grid-3x3"></i> Hexmap
                <% end %>
                <% if can_edit_systems?(@sector, current_user) %>
                  <%= link_to new_system_path(sector_model_system: { sector_id: @sector.id }), class: 'btn btn-primary' do %>
                    <i class="bi bi-plus-circle"></i> New System
                  <% end %>
                  <%= link_to bulk_upload_systems_path(sector_id: @sector.id), class: 'btn btn-success' do %>
                    <i class="bi bi-upload"></i> Bulk Upload
                  <% end %>
                <% end %>
              </div>
            </div>

            <div class="table-responsive">
              <table class="table table-hover align-middle">
                <thead>
                  <tr>
                    <th scope="col">Name</th>
                    <th scope="col" class="text-center">Port</th>
                    <th scope="col" class="text-center">Size</th>
                    <th scope="col" class="text-center">Atmo</th>
                    <th scope="col" class="text-center">Hydro</th>
                    <th scope="col" class="text-center">Pop</th>
                    <th scope="col" class="text-center">Gov</th>
                    <th scope="col" class="text-center">Law</th>
                    <th scope="col" class="text-center">Tech</th>
                    <th scope="col" class="text-center">Bases</th>
                    <th scope="col">Traits</th>
                    <th scope="col" class="text-center">Advisory</th>
                    <th scope="col" class="text-center">Belts</th>
                    <th scope="col" class="text-center">Gas Giants</th>
                    <% if can_edit_systems?(@sector, current_user) %>
                      <th scope="col" class="text-end">Actions</th>
                    <% end %>
                  </tr>
                </thead>
                <tbody>
                  <% unless @systems.blank? %>
                    <% @systems.each do |details| %>
                      <tr>
                        <th scope="row">
                          <div class="d-flex align-items-center">
                            <i class="bi bi-layers fs-5 me-2 text-info"></i>
                            <%= link_to details.name, system_path(details) %>
                          </div>
                        </th>
                        <td class="text-center"><span class="badge bg-secondary-subtle text-secondary-emphasis border"><%= details.starport.split('-').first %></span></td>
                        <td class="text-center"><%= details.planet_size.split('-').first %></td>
                        <td class="text-center"><%= details.atmosphere.split('-').first %></td>
                        <td class="text-center"><%= details.hydrosphere.split('-').last %></td>
                        <td class="text-center"><%= details.population %></td>
                        <td class="text-center"><%= details.goverment.split('-').first %></td>
                        <td class="text-center"><%= details.law %></td>
                        <td class="text-center"><%= details.tech_level %></td>
                        <td class="text-center"><%= details.bases %></td>
                        <td class="small"><%= [details.notes1, details.notes2, details.notes3].reject { |n| n.blank? }.compact.join(', ') %></td>
                        <td class="text-center">
                          <% advisory_code = details.advisory.split(':').first.strip %>
                          <% badge_class = case advisory_code
                                            when 'Green' then 'bg-success'
                                            when 'Amber' then 'bg-warning'
                                            when 'Red' then 'bg-danger'
                                            else 'bg-secondary'
                                          end %>
                          <span class="badge <%= badge_class %>"><%= advisory_code %></span>
                        </td>
                        <td class="text-center"><%= details.asteroid_belts %></td>
                        <td class="text-center"><%= details.gas_giants %></td>
                        <% if can_edit_systems?(@sector, current_user) %>
                          <td class="text-end">
                            <div class="btn-group" role="group">
                              <%= link_to edit_system_path(details), class: 'btn btn-outline-secondary btn-sm', title: 'Edit' do %>
                                <i class="bi bi-pencil"></i>
                              <% end %>
                              <%= link_to system_path(id: details.id, sector_id: @sector.id), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-outline-danger btn-sm', title: 'Delete' do %>
                                <i class="bi bi-trash"></i>
                              <% end %>
                            </div>
                          </td>
                        <% end %>
                      </tr>
                    <% end %>
                  <% end %>
                </tbody>
              </table>
            </div>

            <div class="mt-3">
              <%= link_to sector_path(@sector), class: 'btn btn-secondary' do %>
                <i class="bi bi-arrow-left"></i> Back to Sector
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>

app/views/sector/systems/new.html.erb
<div class="container-fluid">
  <div class="pagetitle">
    <h1>New System</h1>
    <nav>
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/">Home</a></li>
        <li class="breadcrumb-item"><%= link_to "Sectors", sectors_path %></li>
        <li class="breadcrumb-item"><%= link_to @sector.name, sector_path(@sector) %></li>
        <li class="breadcrumb-item"><%= link_to "Systems", systems_path(sector_id: @sector.id) %></li>
        <li class="breadcrumb-item active">New</li>
      </ol>
    </nav>
  </div>

  <section class="section">
    <div class="row justify-content-center">
      <div class="col-lg-10">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">Create New System in <%= @sector.name %> Sector</h5>
            <%= render 'form' %>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>